# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFC_Number', models.CharField(max_length=50)),
                ('RFC_STATUS', models.CharField(choices=[('p', 'Pending'), ('r', 'Processing'), ('f', 'Failed'), ('a', 'Approved'), ('d', 'Canceled'), ('c', 'Completed')], default='p', max_length=1)),
            ],
        ),
    ]
