# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0002_auto_20160128_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodeployment',
            name='Deploy_Date',
            field=models.DateTimeField(null=True, verbose_name='Deploy Date'),
        ),
        migrations.AddField(
            model_name='autodeployment',
            name='Entry_Time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entry Time'),
        ),
        migrations.AddField(
            model_name='autodeployment',
            name='Modify_Time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 28, 8, 56, 31, 519180, tzinfo=utc), verbose_name='Modify Time'),
            preserve_default=False,
        ),
    ]
