# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0003_auto_20160128_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeployment',
            name='Entry_Time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entry Time'),
        ),
    ]
