# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0005_auto_20160128_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Deploy',
        ),
    ]
