# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0007_auto_20160128_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='Modify_Time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Time'),
        ),
    ]
