# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0008_auto_20160128_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='Deploy_Log',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
