# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0009_auto_20160128_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='RFC_STATUS',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
