# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0010_auto_20160129_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='Deploy_Server',
            field=models.CharField(choices=[('deploy_server', 'Deploy_Test'), ('int_sha', 'INT_SHA')], default='deploy_server', max_length=20),
        ),
    ]
