# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoDeployment', '0011_auto_20160129_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='SHOW_STATUS',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='Deploy_Server',
            field=models.CharField(choices=[('deploy_server', 'Deploy_Test'), ('int_sha', 'INT_SHA'), ('sha_prod', 'SHA_Prod')], default='deploy_server', max_length=20),
        ),
    ]
